### ISSUE TITLE
Error 1

### ISSUE THREAD

**Issue by InakiIribarren** [netsmarttech/node-red-contrib-opc-da#22]
Hello,

We are having the next error sometimes when we are accessing to honeywell opc-da

> Error: 1
>     at OPCSyncIO.read (C:\xxxx\node-new\node_modules\node-opc-da\src\opcSyncIO.js:98:19)
>     at processTicksAndRejections (node:internal/process/task_queues:94:5)
>     at async Timeout.doCycle [as _onTimeout] (C:\xxxx\node-new\node_modules\node-red-contrib-opc-da\red\opc-da.js:442:17)_

I have read that this error is related to the amount of data and the update rate. Is this correct?
We are getting less than 100 variables and the update-rate of 60 seconds. 
How can we solve this error?

Thanks a lot!

**Comment by InakiIribarren** [comment]
I have further information. 

I remove some check errors in the function OPCSyncIO.read and we are receiving from the opc-da server some variables with the error -498794494. Anybody knows the reason?

Thanks in advance!
