### ISSUE TITLE
 I can't include more than 170 tags

### ISSUE THREAD

**Issue by VictorStela** [netsmarttech/node-red-contrib-opc-da#7]
Hello, 

I need help, i can't include more than 170 tags and when I separate into two groups the timing between the two groups fails.

Thanks.

**Comment by steuck13** [comment]
Greetings,
Thank you for your report. The 170 tags limit is a known 'issue' that we are still discussing. It was implemented this way to put an upper limit.

Now, what do you mean when you say "timing between the two groups fails"?

Ty for your report.

**Comment by VictorStela** [comment]
I need to collect data from 200 tags every 100 ms. The limit is 170 tags, so I thought of splitting into two groups of 100 tags.

When I create two groups with the 100 ms update rate, I see that one of the nodes is not online and I get this error:

Error: 1
    at OPCSyncIO.read (C:\Users\br94604\.node-red\node_modules\node-opc-da\src\opcSyncIO.js:98:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)d
![Capturar](https://user-images.githubusercontent.com/48191694/72009056-df579000-3233-11ea-9d23-bf33ae9ddb6d.JPG)

**Comment by steuck13** [comment]
Right.

I believe this is probably related to the amount of data vs. the update rate. It`s a known issue but since for most of our needs we never had a 100 ms update rate we didn not find the problem yet.

Would you mind telling me what kind of problem are you trying to solve that has this 100 ms update rate requirement?

Ty

**Comment by VictorStela** [comment]
I need collect an array of 10 samples every second to feed my prediction model, so I need 100 ms update rate.

Do you have any idea how I can do it?

Thanks.

**Comment by steuck13** [comment]
Until I find a way to fix this I believe your best option would be to create separate servers for each group, this way I believe there would be no problem since no resource would be shared between groups.I suggest you give it a try.

I put this issue on my schedule and as soon as I fix it I'll update the node and the lib.

**Comment by VictorStela** [comment]
Good idea, looks like it worked well.

I created three separate servers with 100 ms each and had no more troubles for now.

Any news I tell you.

Thanks @steuck13.

**Comment by VictorStela** [comment]
Now I have three servers and three separate groups, but when one group breaks (OPC server stops communicating with the field device), the other two break too.

**Comment by steuck13** [comment]
How many tags on each group?I believe the same problem is still there, just taking longer to show up. Is it the same error message?

I'm really sorry for this problem our code is creating for you --'. We really didn't anticipate having an application with update rates that much smaller than 1000 ms .

**Comment by VictorStela** [comment]
It's about 80 tags on each group. It's other error message, but now all devices are online and I can't print the error. Whens this happen I send for you.

Don't worry, by your job we have more than one library available for industrial devices on Node-RED.

For now I will work in this way, if you fix any problem I update the library.
